udp ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -60,40 +60,51 @@ jobs:
     - uses: actions/checkout@v2
 
     - run: make -C tests
-    - name: make check
-      run: make check -C tests
-
-  unit-tests-leaks:
-    needs: unit-tests
-    runs-on: ${{ matrix.os }}
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [ubuntu-latest, macos-latest]
-    steps:
-    - uses: actions/checkout@v2
-    - name: Install dependencies
-      run: |
-        set -x
-        if [ "$RUNNER_OS" == "Linux" ]; then
-            sudo apt-get install valgrind
-        elif [ "$RUNNER_OS" == "macOS" ]; then
-            :
-        fi
-    - name: make -C tests
-      run: make -C tests
-    - name: Run leak test
+    # - name: make check
+    #   run: make check -C tests
+    - name: Run test
       run: |
         set -x
         cd tests
         if [ "$RUNNER_OS" == "Linux" ]; then
-            valgrind --leak-check=full --show-leak-kinds=definite,indirect,possible --errors-for-leak-kinds=definite,indirect,possible --error-exitcode=42 ./build/tests
+          valgrind --leak-check=full --show-leak-kinds=definite,indirect,possible --errors-for-leak-kinds=definite,indirect,possible --error-exitcode=42 ./build/tests
         elif [ "$RUNNER_OS" == "macOS" ]; then
-            # MallocStackLoggingNoCompact=1
-            # ./build/tests &
-            # leaks ./build/tests
-            :
-        else
-            echo "$RUNNER_OS not supported"
-            exit 1
+          make check -C tests
         fi
+
+
+
+  # unit-tests-leaks:
+  #   needs: unit-tests
+  #   runs-on: ${{ matrix.os }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       os: [ubuntu-latest, macos-latest]
+  #   steps:
+  #   - uses: actions/checkout@v2
+  #   - name: Install dependencies
+  #     run: |
+  #       set -x
+  #       if [ "$RUNNER_OS" == "Linux" ]; then
+  #           sudo apt-get install valgrind
+  #       elif [ "$RUNNER_OS" == "macOS" ]; then
+  #           :
+  #       fi
+  #   - name: make -C tests
+  #     run: make -C tests
+  #   - name: Run leak test
+  #     run: |
+  #       set -x
+  #       cd tests
+  #       if [ "$RUNNER_OS" == "Linux" ]; then
+  #           valgrind --leak-check=full --show-leak-kinds=definite,indirect,possible --errors-for-leak-kinds=definite,indirect,possible --error-exitcode=42 ./build/tests
+  #       elif [ "$RUNNER_OS" == "macOS" ]; then
+  #           # MallocStackLoggingNoCompact=1
+  #           # ./build/tests &
+  #           # leaks ./build/tests
+  #           :
+  #       else
+  #           echo "$RUNNER_OS not supported"
+  #           exit 1
+  #       fi
